### ISSUE TITLE
Joern Extraction

### ISSUE THREAD

**Issue by jeffyjeff2893** [liucyy/VulPCL#1]
How do you run joern to extract the flattened FCDS and PDG/AST into svg format to be able to run adc and cd feature extracting?

**Comment by qiqicliff** [comment]
@jeffyjeff2893 Have you got the all datasets? I found website of the dataset can not open.It was missed.

**Comment by liucyy** [comment]
> How do you run joern to extract the flattened FCDS and PDG/AST into svg format to be able to run adc and cd feature extracting?

We use joern-0.3.1 to extract information from C/C++ source files and neo4j-community-2.18 to load the information to the database. The SVG files of flattened FCDS and PDG/AST are generated by the newly uploaded "graph_generation.py" file in "data_preprocessing" folder. Hope this helps you.

**Comment by liucyy** [comment]
> @jeffyjeff2893 Have you got the all datasets? I found website of the dataset can not open.It was missed.
Our collected Linux Kernel dataset can be downloaded from https://www.mediafire.com/file/ux2x1m7i2kwom7z/dataset.zip/file.

**Comment by qiqicliff** [comment]
> > @jeffyjeff2893 Have you got the all datasets? I found website of the dataset can not open.It was missed.
> > Our collected Linux Kernel dataset can be downloaded from https://www.mediafire.com/file/ux2x1m7i2kwom7z/dataset.zip/file.

This link is ok!But just a little slow when downloading hhhha,Thank You!!!

**Comment by huangyuyan3** [comment]
> > > [@jeffyjeff2893](https://github.com/jeffyjeff2893) Have you got the all datasets? I found website of the dataset can not open.It was missed.
> > > Our collected Linux Kernel dataset can be downloaded from https://www.mediafire.com/file/ux2x1m7i2kwom7z/dataset.zip/file.
> 
> This link is ok!But just a little slow when downloading hhhha,Thank You!!!

Hi.Could you please tell me if this code can be successfully replicated? And does it match the results presented in the paper?
